// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfeyaertivxapyoysllu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmZXlhZXJ0aXZ4YXB5b3lzbGx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NzI5MTUsImV4cCI6MjA2NDE0ODkxNX0.jxHnL09Ddko1uThfLjxRKQnhpZzbkh_kdNC4utynPCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);